services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm start && tail -f /dev/null"
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - app_data:/app/data

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

volumes:
  app_data:
